# https://swizec.com/blog/using-dynamodb-streams-with-the-serverless-framework/

service: dynamodb-starter-sls
frameworkVersion: '3'

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: 'streaming-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs14.x
  profile: iamadmin
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            # Streams
            - dynamodb:DescribeStream
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListStreams
          Resource:
            - Fn::GetAtt: [ StreamingTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: functions/handler.handler
    events:
      - httpApi: '*'

  streamTrigger:
    handler: functions/streamTrigger.handler
    events:
      - stream:
          type: dynamodb
          arn:
          # Make sure we are referencing the Stream Arn -2 hours KEK
            Fn::GetAtt: [ StreamingTable, StreamArn ]
          batchSize: 5
          startingPosition: LATEST

resources:
  Resources:
    StreamingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
        StreamSpecification:
          StreamViewType: 'NEW_AND_OLD_IMAGES'
        Tags:
          - Key: 'auto-delete'
            Value: 'no'
          - Key: 'auto-stop'
            Value: 'no'

